# This is a basic workflow that is manually triggered
name: Run Jupyter Notebook

# Establecemos permisos para poder hacer commits
permissions:
  contents: write

# Indicamos las ramas asociadas a la acción y el tiempo de ejecución
on:
  push:
    branches: ["main"]
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Los pasos involucrados en la ejecución del trabajo
    steps:
      - name: Revisar repo
        uses: actions/checkout@v4
      - name: Establecer version de python
        uses: actions/setup-python@v2
        with:
          python-version: 3.14
      - name: Instalar dependencias
        run: pip install -r requirements.txt
      - name: Correr Notebook
        run: jupyter execute generacion_base_semanal.ipynb
      - name: Hacer commit y push del archivo
        run: |
          git config user.name "AlejandraFranSi"
          git config user.email "fasa297@gmail.com"
          git add .
          git commit -m "Actualizar reporte"
          git push
